#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  quadEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           cupSpin,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           marbleSpin,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           marbleStop,    tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

Project Title: 3.3.1 Marble Sorter
Team Members: Lena Conde-Araujo, Marianne Smith, Jonathan Nikolaus, Kyle Pearson

*/
int x;
task main() { 

	while(true) {
		SensorValue(quadEncoder)=0;
		startMotor(marbleSpin, -20);
		wait(2);  
		stopMotor(marbleSpin);
		x = x + 1;
		while(x==1) {
			if (SensorValue[lineFollower]>2300) {
				startMotor(marbleStop, 10);
				startMotor(cupSpin, 30);
				untilEncoderCounts(0, quadEncoder);
				stopMotor(marbleStop);
			}
			if (SensorValue[lineFollower]>2600) {
				startMotor(marbleStop, 10);
				startMotor(cupSpin, 30);
				untilEncoderCounts(134, quadEncoder);
				stopMotor(marbleStop);
			}
			if (SensorValue[lineFollower]>1800) {
				startMotor(marbleStop, 10);
				startMotor(cupSpin, 30);
				untilEncoderCounts(360, quadEncoder);
				stopMotor(marbleStop);
			}
			startMotor(marbleStop, -5);
			wait(0.3);
			stopMotor(marbleStop);
			x = x- 1;
		}
	}
}