#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, dgtl1,  quadEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           cupSpin,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           marbleSpin,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           marbleStop,    tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*

Project Title: 3.3.1 Marble Sorter
Team Members: Lena Conde-Araujo, Marianne Smith, Jonathan Nikolaus, Kyle Pearson

*/
int x;
task main() { 
	
	while(true) {
		SensorValue(quadEncoder)=0;
		startMotor(marbleSpin, -30);
		wait(1);  
		stopMotor(marbleSpin);
		x = x + 1;
		while(x==1) {
			if (SensorValue(quadEncoder)=>0 && SensorValue(lineFollower)>2300 && SensorValue(quadEncoder)<=179) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(0, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}
			if (SensorValue(quadEncoder)=>180 && SensorValue(lineFollower)>2300 && SensorValue(quadEncoder)<=359) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(0, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}
			if (SensorValue(quadEncoder)=>360 && SensorValue(lineFollower)>2300) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(0, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}

			if (SensorValue(quadEncoder)=>0 && SensorValue(lineFollower)>2600 && SensorValue(quadEncoder)<=179) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(180, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}
			if (SensorValue(quadEncoder)=>180 && SensorValue(lineFollower)>2600 && SensorValue(quadEncoder)<=359) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(180, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}
			if (SensorValue(quadEncoder)=>360 && SensorValue(lineFollower)>2600) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(180, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}

			if (SensorValue(quadEncoder)=>0 && SensorValue(lineFollower)>1800 && SensorValue(quadEncoder)<=179) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(360, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}
			if (SensorValue(quadEncoder)=>180 && SensorValue(lineFollower)>1800 && SensorValue(quadEncoder)<=359) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(360, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}
			if (SensorValue(quadEncoder)=>360 && SensorValue(lineFollower)>1800) {
				startMotor(cupSpin, 30);
				untilEncoderCounts(360, quadEncoder);
				stopMotor(cupSpin);
				startMotor(marbleStop, -20);
				wait(0.2);
				stopMotor(marbleStop);
			}
			startMotor(marbleStop, 20);
			wait(0.25);
			stopMotor(marbleStop);
			x = x- 1;
		}
	}
}